### ISSUE TITLE
Dependencies from the vignette not in DESCRIPTION

### ISSUE THREAD

**Issue by maelle** [meyera/riskscorer#4]
This issue is part of this [JOSS review](https://github.com/openjournals/joss-reviews/issues/19)

Not all the packages used in the vignette such as `wakefield` and `threejs` are listed in the dependencies in DESCRIPTION (the should be in suggests). I saw this because of an R CHECK error.

**Comment by masalmon** [comment]
`Cairo` is also such a dependency missing in DESCRIPTION.
